[[main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1
    [main.params]
        icon = "home"

[[main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 2
    [main.params]
        icon = "user"

[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 3
    [main.params]
        icon = "code"

[[main]]
    identifier = "archives"
    name = "Archives"
    url = "/archives/"
    weight = 4
    [main.params]
        icon = "archives"

[[social]]
    identifier = "email"
    name = "Email"
    url = "mailto:ha.minh.minhhh@gmail.com"
    weight = 1
    [social.params]
        icon = "email"

[[social]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/minhhh"
    weight = 2
    [social.params]
        icon = "brand-github"

[[social]]
    identifier = "linkedin"
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/huy-minh-ha"
    weight = 3
    [social.params]
        icon = "brand-linkedin"

[[social]]
    identifier = "twitter"
    name = "Twitter"
    url = "https://twitter.com/utsace"
    weight = 4
    [social.params]
        icon = "brand-twitter"

[[social]]
    identifier = "facebook"
    name = "Facebook"
    url = "https://www.facebook.com/minh.ha.hanoi"
    weight = 5
    [social.params]
        icon = "brand-facebook"

[[social]]
    identifier = "rss"
    name = "RSS"
    url = "/index.xml"
    weight = 6
    [social.params]
        icon = "rss"

