name: Deploy Hugo
on:
  push:
    branches: [source]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10
        with:
          submodules: true
          fetch-depth: 0
      - uses: peaceiris/actions-hugo@940247d08e49bd08fdbf94e0294d90305f6cb6f9
        with:
          hugo-version: latest
          extended: true
      - run: cd blog && hugo --minify
      - uses: peaceiris/actions-gh-pages@0d8205302eaa499bdb90a1a37dfa11de9e209f92
        with:
          publish_dir: ./blog/public
          publish_branch: main
          cname: minhhh.github.io
          github_token: ${{ secrets.GITHUB_TOKEN }}
