name: Deploy Hugo
on:
  push:
    branches: [source]
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
        with:
          submodules: true
          fetch-depth: 0
      - uses: peaceiris/actions-hugo@16361eb4acea8698b220b76c0d4e84e1fd22c61d
        with:
          hugo-version: latest
          extended: true
      - run: cd blog && hugo --minify
      - uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847
        with:
          publish_dir: ./blog/public
          publish_branch: main
          cname: minhhh.github.io
